import math

# game settings
RES = WIDTH, HEIGHT = 1600, 900
# RES = WIDTH, HEIGHT = 1920, 1080
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 0

PLAYER_POS = 1.5, 5  # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100
PLAYER_SPRINT_MULT = 1.8
PLAYER_CROUCH_MULT = 0.45
PLAYER_CROUCH_COLLIDER_SCALE = 0.8
STAMINA_MAX = 100
STAMINA_DRAIN_RATE = 0.05  # per ms while sprinting
STAMINA_RECOVER_RATE = 0.03  # per ms while not sprinting

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)
CROSSHAIR_COLOR = (230, 230, 230)
CROSSHAIR_SIZE = 16
CROSSHAIR_THICKNESS = 2
RELOAD_BAR_SIZE = (180, 10)
RELOAD_BAR_COLOR = (200, 180, 40)
RELOAD_BAR_BG_COLOR = (40, 40, 40)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2